apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          imagePullPolicy: Always
          image: pavankumar07s/kube_network_practice
          # livenessProbe:
          #   httpGet:
          #     path: /signup
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          env:
            - name: AUTH_ADDRESS
              # value: "10.99.104.252"
              value: "auth-service.default"
