apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "app/config/"
      readOnly: true
  volumes:
  - name: foo
    configMap:
      name: myconfigmap